# id, set, skill, pair, prompt, reference, [(wrong_model, wrong_query)], sortcol (index in result the order depends on, or None)
ITEMS = [
# ---------- PRACTICE: S1 group + one aggregate ----------
("P02","practice","S1","H02","What is the average fare in each city? Show city and avg_fare rounded to 1 decimal, sorted by city name, A to Z.",
 "SELECT city, ROUND(AVG(fare),1) AS avg_fare FROM rides GROUP BY city ORDER BY city",
 [("no GROUP BY","SELECT city, ROUND(AVG(fare),1) FROM rides"),
  ("groups by the wrong column","SELECT city, ROUND(AVG(fare),1) FROM rides GROUP BY driver ORDER BY city")],None),
("P04","practice","S1","H03","How far has each driver driven in total? Show driver and total_km rounded to 1 decimal, highest total first.",
 "SELECT driver, ROUND(SUM(distance_km),1) AS total_km FROM rides GROUP BY driver ORDER BY total_km DESC",
 [("COUNT instead of SUM","SELECT driver, COUNT(distance_km) AS total_km FROM rides GROUP BY driver ORDER BY total_km DESC"),
  ("no GROUP BY","SELECT driver, ROUND(SUM(distance_km),1) FROM rides")],1),
("P05","practice","S1","H01","How many deploys went to each environment of each service? Show service, env and deploy_count, sorted by service name then env name.",
 "SELECT service, env, COUNT(*) AS deploy_count FROM deploys GROUP BY service, env ORDER BY service, env",
 [("groups by one column only","SELECT service, env, COUNT(*) FROM deploys GROUP BY service ORDER BY service, env"),
  ("groups by env only","SELECT service, env, COUNT(*) FROM deploys GROUP BY env ORDER BY service, env")],None),
("P07","practice","S2","H04","Count only the failed deploys for each service. Show service and failed_count, sorted by service name, A to Z.",
 "SELECT service, COUNT(*) AS failed_count FROM deploys WHERE status = 'failed' GROUP BY service ORDER BY service",
 [("row filter in HAVING","SELECT service, COUNT(*) FROM deploys GROUP BY service HAVING status = 'failed' ORDER BY service"),
  ("no filter","SELECT service, COUNT(*) FROM deploys GROUP BY service ORDER BY service")],None),
("P08","practice","S2","H05","Looking only at rides longer than 10 km, what is the average fare in each city? Show city and avg_fare rounded to 1 decimal, sorted by city name, A to Z.",
 "SELECT city, ROUND(AVG(fare),1) AS avg_fare FROM rides WHERE distance_km > 10 GROUP BY city ORDER BY city",
 [("row filter in HAVING","SELECT city, ROUND(AVG(fare),1) FROM rides GROUP BY city HAVING distance_km > 10 ORDER BY city"),
  ("no filter","SELECT city, ROUND(AVG(fare),1) FROM rides GROUP BY city ORDER BY city")],None),
("P09","practice","S2","H06","How many P1 tickets has each team closed? Show team and closed_p1, sorted by team name, A to Z.",
 "SELECT team, COUNT(*) AS closed_p1 FROM tickets WHERE priority = 'P1' AND status = 'closed' GROUP BY team ORDER BY team",
 [("only one of the two conditions","SELECT team, COUNT(*) FROM tickets WHERE priority = 'P1' GROUP BY team ORDER BY team"),
  ("conditions in HAVING","SELECT team, COUNT(*) FROM tickets GROUP BY team HAVING priority = 'P1' AND status = 'closed' ORDER BY team")],None),
("P10","practice","S2",None,"Considering prod deploys only, what is the average deploy duration per service? Show service and avg_seconds rounded to 1 decimal, slowest first.",
 "SELECT service, ROUND(AVG(duration_sec),1) AS avg_seconds FROM deploys WHERE env = 'prod' GROUP BY service ORDER BY avg_seconds DESC",
 [("row filter in HAVING","SELECT service, ROUND(AVG(duration_sec),1) AS avg_seconds FROM deploys GROUP BY service HAVING env = 'prod' ORDER BY avg_seconds DESC"),
  ("no filter","SELECT service, ROUND(AVG(duration_sec),1) AS avg_seconds FROM deploys GROUP BY service ORDER BY avg_seconds DESC")],1),
("P12","practice","S2",None,"Among closed tickets only, what is the longest close time for each priority? Show priority and longest_hours, sorted by priority, P1 first.",
 "SELECT priority, MAX(hours_to_close) AS longest_hours FROM tickets WHERE status = 'closed' GROUP BY priority ORDER BY priority",
 [("no filter","SELECT priority, MAX(hours_to_close) FROM tickets GROUP BY priority ORDER BY priority"),
  ("row filter in HAVING","SELECT priority, MAX(hours_to_close) FROM tickets GROUP BY priority HAVING status = 'closed' ORDER BY priority")],None),
("P13","practice","S2",None,"Ignoring the auth service, how many successful deploys did each environment get? Show env and success_count, sorted by env name, A to Z.",
 "SELECT env, COUNT(*) AS success_count FROM deploys WHERE status = 'success' AND service <> 'auth' GROUP BY env ORDER BY env",
 [("forgets to exclude auth","SELECT env, COUNT(*) FROM deploys WHERE status = 'success' GROUP BY env ORDER BY env"),
  ("row filters in HAVING","SELECT env, COUNT(*) FROM deploys GROUP BY env HAVING status = 'success' AND service <> 'auth' ORDER BY env")],None),
# ---------- PRACTICE: S3 filter groups after aggregating ----------
("P14","practice","S3","H07","Which services have been deployed more than 6 times? Show service and deploy_count, sorted by service name, A to Z.",
 "SELECT service, COUNT(*) AS deploy_count FROM deploys GROUP BY service HAVING COUNT(*) > 6 ORDER BY service",
 [("aggregate in WHERE","SELECT service, COUNT(*) FROM deploys WHERE COUNT(*) > 6 GROUP BY service ORDER BY service"),
  ("filters rows on deploy_id","SELECT service, COUNT(*) FROM deploys WHERE deploy_id > 6 GROUP BY service ORDER BY service")],None),
("P15","practice","S3","H08","Which cities have an average fare above 200? Show city and avg_fare rounded to 1 decimal, highest average first.",
 "SELECT city, ROUND(AVG(fare),1) AS avg_fare FROM rides GROUP BY city HAVING AVG(fare) > 200 ORDER BY avg_fare DESC",
 [("row filter instead of group filter","SELECT city, ROUND(AVG(fare),1) AS avg_fare FROM rides WHERE fare > 200 GROUP BY city ORDER BY avg_fare DESC"),
  ("aggregate in WHERE","SELECT city, ROUND(AVG(fare),1) AS avg_fare FROM rides WHERE AVG(fare) > 200 GROUP BY city ORDER BY avg_fare DESC")],1),
("P16","practice","S3","H09","Which teams have spent more than 300 hours in total closing tickets? Show team and total_hours, sorted by team name, A to Z.",
 "SELECT team, SUM(hours_to_close) AS total_hours FROM tickets GROUP BY team HAVING SUM(hours_to_close) > 300 ORDER BY team",
 [("row filter instead of group filter","SELECT team, SUM(hours_to_close) FROM tickets WHERE hours_to_close > 30 GROUP BY team ORDER BY team"),
  ("aggregate in WHERE","SELECT team, SUM(hours_to_close) FROM tickets WHERE SUM(hours_to_close) > 300 GROUP BY team ORDER BY team")],None),
("P17","practice","S3",None,"Which drivers have done at least 7 rides? Show driver and ride_count, most rides first.",
 "SELECT driver, COUNT(*) AS ride_count FROM rides GROUP BY driver HAVING COUNT(*) >= 7 ORDER BY ride_count DESC",
 [("aggregate in WHERE","SELECT driver, COUNT(*) AS ride_count FROM rides WHERE COUNT(*) >= 7 GROUP BY driver ORDER BY ride_count DESC"),
  ("no HAVING","SELECT driver, COUNT(*) AS ride_count FROM rides GROUP BY driver ORDER BY ride_count DESC")],1),
("P18","practice","S3",None,"Which services have never had a deploy faster than 60 seconds? Show service and fastest_seconds, sorted by service name, A to Z.",
 "SELECT service, MIN(duration_sec) AS fastest_seconds FROM deploys GROUP BY service HAVING MIN(duration_sec) >= 60 ORDER BY service",
 [("row filter instead of group filter","SELECT service, MIN(duration_sec) FROM deploys WHERE duration_sec >= 60 GROUP BY service ORDER BY service"),
  ("aggregate in WHERE","SELECT service, MIN(duration_sec) FROM deploys WHERE MIN(duration_sec) >= 60 GROUP BY service ORDER BY service")],None),
("P19","practice","S3",None,"Which priorities take less than 45 hours to close on average? Show priority and avg_hours rounded to 1 decimal, sorted by priority, P1 first.",
 "SELECT priority, ROUND(AVG(hours_to_close),1) AS avg_hours FROM tickets GROUP BY priority HAVING AVG(hours_to_close) < 45 ORDER BY priority",
 [("row filter instead of group filter","SELECT priority, ROUND(AVG(hours_to_close),1) FROM tickets WHERE hours_to_close < 45 GROUP BY priority ORDER BY priority"),
  ("no HAVING","SELECT priority, ROUND(AVG(hours_to_close),1) FROM tickets GROUP BY priority ORDER BY priority")],None),
("P20","practice","S3",None,"Which cities have more than 100 km of rides in total? Show city and total_km rounded to 1 decimal, highest first.",
 "SELECT city, ROUND(SUM(distance_km),1) AS total_km FROM rides GROUP BY city HAVING SUM(distance_km) > 100 ORDER BY total_km DESC",
 [("row filter instead of group filter","SELECT city, ROUND(SUM(distance_km),1) AS total_km FROM rides WHERE distance_km > 10 GROUP BY city ORDER BY total_km DESC"),
  ("aggregate in WHERE","SELECT city, ROUND(SUM(distance_km),1) AS total_km FROM rides WHERE SUM(distance_km) > 100 GROUP BY city ORDER BY total_km DESC")],1),
# ---------- HELD-OUT ----------
("H01","heldout","S1","P05","The ops lead wants ride volume by city. List each city with its number of rides (city, ride_count), busiest city first.",
 "SELECT city, COUNT(*) AS ride_count FROM rides GROUP BY city ORDER BY ride_count DESC",
 [("no GROUP BY","SELECT city, COUNT(*) FROM rides")],1),
("H02","heldout","S1","P02","Is staging slower than prod? Show each env with its average deploy duration in seconds, rounded to 1 decimal (env, avg_seconds), sorted by env name, A to Z.",
 "SELECT env, ROUND(AVG(duration_sec),1) AS avg_seconds FROM deploys GROUP BY env ORDER BY env",
 [("no GROUP BY","SELECT env, ROUND(AVG(duration_sec),1) FROM deploys")],None),
("H03","heldout","S1","P04","What is the single highest fare each driver has earned? Show driver and top_fare, sorted by driver name, A to Z.",
 "SELECT driver, MAX(fare) AS top_fare FROM rides GROUP BY driver ORDER BY driver",
 [("no GROUP BY","SELECT driver, MAX(fare) FROM rides")],None),
("H04","heldout","S2","P07","How many tickets are still open for each team? Show team and open_tickets, most open first.",
 "SELECT team, COUNT(*) AS open_tickets FROM tickets WHERE status = 'open' GROUP BY team ORDER BY open_tickets DESC",
 [("row filter in HAVING","SELECT team, COUNT(*) AS open_tickets FROM tickets GROUP BY team HAVING status = 'open' ORDER BY open_tickets DESC")],1),
("H05","heldout","S2","P08","When deploys fail, how long do they run? Using failed deploys only, show each service with its average duration rounded to 1 decimal (service, avg_seconds), sorted by service name, A to Z.",
 "SELECT service, ROUND(AVG(duration_sec),1) AS avg_seconds FROM deploys WHERE status = 'failed' GROUP BY service ORDER BY service",
 [("row filter in HAVING","SELECT service, ROUND(AVG(duration_sec),1) FROM deploys GROUP BY service HAVING status = 'failed' ORDER BY service")],None),
("H06","heldout","S2","P09","Total fare per city, counting only rides rated 5. Show city and fare_total, sorted by city name, A to Z.",
 "SELECT city, SUM(fare) AS fare_total FROM rides WHERE rating = 5 GROUP BY city ORDER BY city",
 [("row filter in HAVING","SELECT city, SUM(fare) FROM rides GROUP BY city HAVING rating = 5 ORDER BY city")],None),
("H07","heldout","S3","P14","List the teams that have raised more than 8 tickets, with how many (team, ticket_count), sorted by team name, A to Z.",
 "SELECT team, COUNT(*) AS ticket_count FROM tickets GROUP BY team HAVING COUNT(*) > 8 ORDER BY team",
 [("aggregate in WHERE","SELECT team, COUNT(*) FROM tickets WHERE COUNT(*) > 8 GROUP BY team ORDER BY team")],None),
("H08","heldout","S3","P15","Which services average more than 175 seconds per deploy? Show service and avg_seconds rounded to 1 decimal, sorted by service name, A to Z.",
 "SELECT service, ROUND(AVG(duration_sec),1) AS avg_seconds FROM deploys GROUP BY service HAVING AVG(duration_sec) > 175 ORDER BY service",
 [("row filter instead of group filter","SELECT service, ROUND(AVG(duration_sec),1) FROM deploys WHERE duration_sec > 175 GROUP BY service ORDER BY service")],None),
("H09","heldout","S3","P16","Which drivers have earned more than 1500 in total fares? Show driver and total_fare, highest earner first.",
 "SELECT driver, SUM(fare) AS total_fare FROM rides GROUP BY driver HAVING SUM(fare) > 1500 ORDER BY total_fare DESC",
 [("row filter instead of group filter","SELECT driver, SUM(fare) AS total_fare FROM rides WHERE fare > 150 GROUP BY driver ORDER BY total_fare DESC")],1),
("H10","heldout","S4","P10+P14","Looking at prod deploys only, which services have at least 3 of them? Show service and prod_deploys, most first.",
 "SELECT service, COUNT(*) AS prod_deploys FROM deploys WHERE env = 'prod' GROUP BY service HAVING COUNT(*) >= 3 ORDER BY prod_deploys DESC",
 [("both filters in HAVING","SELECT service, COUNT(*) AS prod_deploys FROM deploys GROUP BY service HAVING env = 'prod' AND COUNT(*) >= 3 ORDER BY prod_deploys DESC"),
  ("forgets the prod filter","SELECT service, COUNT(*) AS prod_deploys FROM deploys GROUP BY service HAVING COUNT(*) >= 3 ORDER BY prod_deploys DESC")],1),
("H11","heldout","S4","P08+P15","For rides longer than 5 km, which cities average a fare above 250? Show city and avg_fare rounded to 1 decimal, highest average first.",
 "SELECT city, ROUND(AVG(fare),1) AS avg_fare FROM rides WHERE distance_km > 5 GROUP BY city HAVING AVG(fare) > 250 ORDER BY avg_fare DESC",
 [("forgets the km filter","SELECT city, ROUND(AVG(fare),1) AS avg_fare FROM rides GROUP BY city HAVING AVG(fare) > 250 ORDER BY avg_fare DESC"),
  ("group filter as a row filter","SELECT city, ROUND(AVG(fare),1) AS avg_fare FROM rides WHERE distance_km > 5 AND fare > 250 GROUP BY city ORDER BY avg_fare DESC")],1),
("H12","heldout","S4","P12+P19","Among closed tickets, which teams take more than 35 hours to close on average? Show team and avg_hours rounded to 1 decimal, slowest first.",
 "SELECT team, ROUND(AVG(hours_to_close),1) AS avg_hours FROM tickets WHERE status = 'closed' GROUP BY team HAVING AVG(hours_to_close) > 35 ORDER BY avg_hours DESC",
 [("forgets the closed filter","SELECT team, ROUND(AVG(hours_to_close),1) AS avg_hours FROM tickets GROUP BY team HAVING AVG(hours_to_close) > 35 ORDER BY avg_hours DESC"),
  ("group filter as a row filter","SELECT team, ROUND(AVG(hours_to_close),1) AS avg_hours FROM tickets WHERE status = 'closed' AND hours_to_close > 35 GROUP BY team ORDER BY avg_hours DESC")],1),
]
