CREATE TABLE deploys (deploy_id INTEGER PRIMARY KEY, service TEXT, env TEXT, status TEXT, duration_sec INTEGER);
CREATE TABLE tickets (ticket_id INTEGER PRIMARY KEY, team TEXT, priority TEXT, status TEXT, hours_to_close INTEGER);
CREATE TABLE rides (ride_id INTEGER PRIMARY KEY, city TEXT, driver TEXT, fare INTEGER, distance_km REAL, rating INTEGER);
INSERT INTO deploys VALUES (1, 'search', 'staging', 'success', 64);
INSERT INTO deploys VALUES (2, 'auth', 'staging', 'success', 69);
INSERT INTO deploys VALUES (3, 'payments', 'staging', 'failed', 262);
INSERT INTO deploys VALUES (4, 'notify', 'staging', 'failed', 322);
INSERT INTO deploys VALUES (5, 'notify', 'staging', 'success', 103);
INSERT INTO deploys VALUES (6, 'billing', 'staging', 'success', 243);
INSERT INTO deploys VALUES (7, 'auth', 'staging', 'failed', 108);
INSERT INTO deploys VALUES (8, 'search', 'prod', 'failed', 100);
INSERT INTO deploys VALUES (9, 'payments', 'prod', 'success', 389);
INSERT INTO deploys VALUES (10, 'billing', 'staging', 'success', 367);
INSERT INTO deploys VALUES (11, 'billing', 'prod', 'failed', 72);
INSERT INTO deploys VALUES (12, 'payments', 'staging', 'success', 294);
INSERT INTO deploys VALUES (13, 'payments', 'prod', 'success', 278);
INSERT INTO deploys VALUES (14, 'payments', 'prod', 'success', 167);
INSERT INTO deploys VALUES (15, 'billing', 'staging', 'failed', 193);
INSERT INTO deploys VALUES (16, 'payments', 'prod', 'success', 269);
INSERT INTO deploys VALUES (17, 'auth', 'staging', 'failed', 254);
INSERT INTO deploys VALUES (18, 'billing', 'prod', 'failed', 290);
INSERT INTO deploys VALUES (19, 'notify', 'staging', 'success', 79);
INSERT INTO deploys VALUES (20, 'payments', 'prod', 'success', 219);
INSERT INTO deploys VALUES (21, 'payments', 'prod', 'success', 273);
INSERT INTO deploys VALUES (22, 'auth', 'staging', 'success', 282);
INSERT INTO deploys VALUES (23, 'auth', 'staging', 'success', 198);
INSERT INTO deploys VALUES (24, 'payments', 'prod', 'failed', 237);
INSERT INTO deploys VALUES (25, 'search', 'staging', 'success', 221);
INSERT INTO deploys VALUES (26, 'billing', 'staging', 'success', 151);
INSERT INTO deploys VALUES (27, 'search', 'staging', 'success', 243);
INSERT INTO deploys VALUES (28, 'notify', 'prod', 'failed', 269);
INSERT INTO deploys VALUES (29, 'notify', 'prod', 'success', 260);
INSERT INTO deploys VALUES (30, 'payments', 'prod', 'success', 223);
INSERT INTO deploys VALUES (31, 'notify', 'staging', 'failed', 130);
INSERT INTO deploys VALUES (32, 'billing', 'staging', 'success', 46);
INSERT INTO deploys VALUES (33, 'notify', 'staging', 'failed', 42);
INSERT INTO deploys VALUES (34, 'billing', 'prod', 'success', 352);
INSERT INTO deploys VALUES (35, 'payments', 'prod', 'success', 393);
INSERT INTO deploys VALUES (36, 'payments', 'staging', 'success', 388);
INSERT INTO deploys VALUES (37, 'payments', 'prod', 'success', 241);
INSERT INTO deploys VALUES (38, 'auth', 'prod', 'success', 71);
INSERT INTO deploys VALUES (39, 'billing', 'staging', 'success', 265);
INSERT INTO deploys VALUES (40, 'billing', 'staging', 'success', 66);
INSERT INTO tickets VALUES (1, 'mobile', 'P1', 'closed', 69);
INSERT INTO tickets VALUES (2, 'mobile', 'P2', 'open', 10);
INSERT INTO tickets VALUES (3, 'web', 'P3', 'closed', 82);
INSERT INTO tickets VALUES (4, 'platform', 'P2', 'open', 61);
INSERT INTO tickets VALUES (5, 'mobile', 'P1', 'open', 60);
INSERT INTO tickets VALUES (6, 'data', 'P2', 'closed', 19);
INSERT INTO tickets VALUES (7, 'mobile', 'P3', 'closed', 34);
INSERT INTO tickets VALUES (8, 'data', 'P3', 'closed', 3);
INSERT INTO tickets VALUES (9, 'web', 'P3', 'closed', 89);
INSERT INTO tickets VALUES (10, 'mobile', 'P3', 'closed', 83);
INSERT INTO tickets VALUES (11, 'mobile', 'P3', 'open', 67);
INSERT INTO tickets VALUES (12, 'platform', 'P1', 'closed', 29);
INSERT INTO tickets VALUES (13, 'platform', 'P3', 'closed', 25);
INSERT INTO tickets VALUES (14, 'web', 'P2', 'open', 30);
INSERT INTO tickets VALUES (15, 'web', 'P3', 'closed', 4);
INSERT INTO tickets VALUES (16, 'mobile', 'P2', 'closed', 25);
INSERT INTO tickets VALUES (17, 'platform', 'P2', 'open', 45);
INSERT INTO tickets VALUES (18, 'platform', 'P1', 'closed', 30);
INSERT INTO tickets VALUES (19, 'data', 'P1', 'closed', 62);
INSERT INTO tickets VALUES (20, 'mobile', 'P2', 'open', 45);
INSERT INTO tickets VALUES (21, 'mobile', 'P3', 'closed', 50);
INSERT INTO tickets VALUES (22, 'web', 'P2', 'open', 56);
INSERT INTO tickets VALUES (23, 'platform', 'P1', 'open', 51);
INSERT INTO tickets VALUES (24, 'data', 'P2', 'open', 11);
INSERT INTO tickets VALUES (25, 'web', 'P1', 'open', 4);
INSERT INTO tickets VALUES (26, 'web', 'P3', 'open', 84);
INSERT INTO tickets VALUES (27, 'web', 'P3', 'open', 61);
INSERT INTO tickets VALUES (28, 'platform', 'P1', 'closed', 17);
INSERT INTO tickets VALUES (29, 'mobile', 'P1', 'open', 84);
INSERT INTO tickets VALUES (30, 'mobile', 'P3', 'open', 18);
INSERT INTO tickets VALUES (31, 'data', 'P1', 'open', 28);
INSERT INTO tickets VALUES (32, 'mobile', 'P2', 'closed', 65);
INSERT INTO tickets VALUES (33, 'web', 'P3', 'closed', 70);
INSERT INTO tickets VALUES (34, 'data', 'P1', 'closed', 46);
INSERT INTO tickets VALUES (35, 'data', 'P3', 'closed', 67);
INSERT INTO tickets VALUES (36, 'data', 'P3', 'closed', 20);
INSERT INTO rides VALUES (1, 'Delhi', 'Divya', 219, 13.3, 5);
INSERT INTO rides VALUES (2, 'Indore', 'Bela', 50, 1.6, 5);
INSERT INTO rides VALUES (3, 'Delhi', 'Farhan', 232, 15.4, 4);
INSERT INTO rides VALUES (4, 'Indore', 'Farhan', 307, 16.9, 3);
INSERT INTO rides VALUES (5, 'Delhi', 'Bela', 333, 21.4, 4);
INSERT INTO rides VALUES (6, 'Delhi', 'Farhan', 100, 2.4, 5);
INSERT INTO rides VALUES (7, 'Delhi', 'Divya', 80, 2.1, 5);
INSERT INTO rides VALUES (8, 'Indore', 'Farhan', 362, 23.4, 4);
INSERT INTO rides VALUES (9, 'Indore', 'Divya', 237, 11.7, 4);
INSERT INTO rides VALUES (10, 'Jaipur', 'Farhan', 275, 17.2, 5);
INSERT INTO rides VALUES (11, 'Delhi', 'Divya', 130, 4.6, 4);
INSERT INTO rides VALUES (12, 'Pune', 'Divya', 62, 3.1, 4);
INSERT INTO rides VALUES (13, 'Delhi', 'Bela', 324, 16.6, 4);
INSERT INTO rides VALUES (14, 'Pune', 'Divya', 103, 4.7, 3);
INSERT INTO rides VALUES (15, 'Kochi', 'Bela', 242, 10.5, 4);
INSERT INTO rides VALUES (16, 'Kochi', 'Farhan', 132, 5.1, 4);
INSERT INTO rides VALUES (17, 'Jaipur', 'Chetan', 175, 11.0, 4);
INSERT INTO rides VALUES (18, 'Indore', 'Divya', 92, 1.9, 3);
INSERT INTO rides VALUES (19, 'Indore', 'Farhan', 188, 10.1, 5);
INSERT INTO rides VALUES (20, 'Delhi', 'Bela', 346, 23.1, 3);
INSERT INTO rides VALUES (21, 'Delhi', 'Bela', 149, 7.5, 4);
INSERT INTO rides VALUES (22, 'Jaipur', 'Divya', 307, 19.9, 5);
INSERT INTO rides VALUES (23, 'Indore', 'Divya', 409, 22.2, 4);
INSERT INTO rides VALUES (24, 'Delhi', 'Gita', 82, 3.5, 5);
INSERT INTO rides VALUES (25, 'Jaipur', 'Amit', 393, 21.6, 3);
INSERT INTO rides VALUES (26, 'Delhi', 'Farhan', 311, 19.5, 3);
INSERT INTO rides VALUES (27, 'Delhi', 'Divya', 116, 7.5, 4);
INSERT INTO rides VALUES (28, 'Jaipur', 'Chetan', 423, 23.9, 4);
INSERT INTO rides VALUES (29, 'Pune', 'Amit', 65, 2.5, 4);
INSERT INTO rides VALUES (30, 'Pune', 'Chetan', 126, 2.6, 4);
INSERT INTO rides VALUES (31, 'Pune', 'Chetan', 254, 13.4, 5);
INSERT INTO rides VALUES (32, 'Jaipur', 'Chetan', 244, 16.6, 4);
INSERT INTO rides VALUES (33, 'Delhi', 'Gita', 106, 2.3, 5);
INSERT INTO rides VALUES (34, 'Indore', 'Divya', 370, 23.5, 5);
INSERT INTO rides VALUES (35, 'Kochi', 'Gita', 127, 3.9, 5);
INSERT INTO rides VALUES (36, 'Kochi', 'Farhan', 333, 20.3, 4);
INSERT INTO rides VALUES (37, 'Jaipur', 'Bela', 430, 23.6, 4);
INSERT INTO rides VALUES (38, 'Jaipur', 'Amit', 174, 10.6, 3);
INSERT INTO rides VALUES (39, 'Jaipur', 'Divya', 73, 3.1, 3);
INSERT INTO rides VALUES (40, 'Kochi', 'Farhan', 142, 3.4, 4);
INSERT INTO rides VALUES (41, 'Jaipur', 'Amit', 278, 15.0, 4);
INSERT INTO rides VALUES (42, 'Kochi', 'Amit', 113, 5.0, 4);
